<a href="https://colab.research.google.com/github/Jessicagarg258/data-analytics/blob/main/assgn_5feb_202301027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)


[5 4 6 3 2 1]


In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = arr1 == arr2

print(comparison)


[[ True  True]
 [ True  True]]


In [4]:
a = np.array([1,2,3,4,5,1,2,1,1,1])
b = np.array([1,1,1, 2, 3, 4, 2, 4, 3, 3])
print(f"The most frequent value in  first array is : {np.bincount(a).argmax()}")
print(f"The index of most frequent values of first array are {np.where(a==(np.bincount(a).argmax()))}")
print(f"The most frequent value in  second array is : {np.bincount(b).argmax()}")
print(f"The index of most frequent values of second array are {np.where(b==(np.bincount(b).argmax()))}")

The most frequent value in  first array is : 1
The index of most frequent values of first array are (array([0, 5, 7, 8, 9]),)
The most frequent value in  second array is : 1
The index of most frequent values of second array are (array([0, 1, 2]),)


In [5]:
y = np.matrix("[4, 1, 9; 12, 3, 1; 4, 5, 6]")
print(y)
print(f"The sum of matrix is {np.sum(y)}")
print(f"The sum of all rows are {y.sum(axis=1)}")
print(f"The sum of all columns  are {y.sum(axis=0)}")

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
The sum of matrix is 45
The sum of all rows are [[14]
 [16]
 [15]]
The sum of all columns  are [[20  9 16]]
