<a href="https://colab.research.google.com/github/Jessicagarg258/data-analytics/blob/main/LabEval_grp2_202301027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
array=np.array([10,52,62,16,16,54,453])

#1
x=np.sort(array)
print(x)

#2
y=np.argwhere(x)
print(y)

#3
k=4
print("smallest element")
print(x[:k])

#4
k=5
print("largest element")
print(x[2:])

[ 10  16  16  52  54  62 453]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
smallest element
[10 16 16 52]
largest element
[ 16  52  54  62 453]
